apiVersion: apps/v1
kind: Deployment
metadata:
  # Usa el helper para generar un nombre único basado en el release
  name: {{ include "my-app.fullname" . }}
  labels:
    {{ include "my-app.labels" . | nindent 4 }}
spec:
  # Configuración de réplicas para Alta Disponibilidad (Punto 4.b)
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "my-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "my-app.selectorLabels" . | nindent 8 }}
    spec:
      # Punto 3: Seguridad (No-Root) para pasar Semgrep
      securityContext:
        allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
        readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      containers: 
        - name: my-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

          # Punto 5: Observabilidad y Alta Disponibilidad
          livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{ toYaml .Values.readinessProbe | nindent 12 }}

          resources:
            {{ toYaml .Values.resources | nindent 12 }}